package com.mrbachorecz.noalcohol.maincard

val sobrietyQuotes = listOf(
    "The first step towards getting somewhere is to decide you’re not going to stay where you are.",
    "One day at a time.",
    "Your best days are ahead of you.",
    "Recovery is not for people who need it, it’s for people who want it.",
    "It does not matter how slowly you go as long as you do not stop. — Confucius",
    "Small steps every day.",
    "You are stronger than you think.",
    "Sobriety is a journey, not a destination.",
    "Believe you can and you’re halfway there. — Theodore Roosevelt",
    "Progress, not perfection.",
    "Every day is a new beginning.",
    "The only way out is through.",
    "You don’t have to see the whole staircase, just take the first step. — Martin Luther King Jr.",
    "Difficult roads often lead to beautiful destinations.",
    "Stay patient and trust your journey.",
    "Your future is created by what you do today, not tomorrow.",
    "Strength grows in the moments when you think you can’t go on but you keep going anyway.",
    "You are not your addiction.",
    "Every accomplishment starts with the decision to try.",
    "Let your faith be bigger than your fear.",
    "Sobriety is self-respect in action.",
    "You are worth the fight.",
    "The comeback is always stronger than the setback.",
    "Don’t let the past steal your present.",
    "You didn’t come this far to only come this far.",
    "Healing is not linear.",
    "Your story isn’t over yet.",
    "You are capable of amazing things.",
    "One step at a time is progress.",
    "You are not alone in this journey.",
    "Hope is stronger than fear.",
    "Choose recovery every day.",
    "Your life matters.",
    "Be proud of how far you’ve come.",
    "You are more than your mistakes.",
    "Stay strong, your future self will thank you.",
    "Recovery is possible.",
    "You have the power to change.",
    "Let go of what you can’t control.",
    "Celebrate every victory, no matter how small.",
    "You are enough.",
    "Keep moving forward.",
    "Your struggle is part of your story.",
    "Don’t give up on yourself.",
    "You are braver than you believe.",
    "Sobriety is a gift you give yourself.",
    "Every day sober is a victory.",
    "You are rewriting your story.",
    "The best view comes after the hardest climb.",
    "Your journey inspires others.",
    "The only journey is the one within. — Rainer Maria Rilke",
    "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
    "The greatest glory in living lies not in never falling, but in rising every time we fall. — Nelson Mandela",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. — Winston Churchill",
    "The best way out is always through. — Robert Frost",
    "Our greatest glory is not in never falling, but in rising every time we fall. — Confucius",
    "You must do the things you think you cannot do. — Eleanor Roosevelt",
    "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
    "It always seems impossible until it’s done. — Nelson Mandela",
    "Every day is a chance to get stronger.",
    "You are the author of your own story.",
    "Let today be the start of something new.",
    "Your present circumstances don’t determine where you can go; they merely determine where you start.",
    "You are not defined by your past.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "You are capable of more than you know.",
    "Don’t count the days, make the days count.",
    "You are a work in progress, and that’s okay.",
    "The struggle you’re in today is developing the strength you need for tomorrow.",
    "You have survived 100% of your worst days.",
    "Your journey is unique, embrace it.",
    "You are stronger than your excuses.",
    "Let your courage be bigger than your fear.",
    "You are making progress, even if it’s hard to see.",
    "Every step forward is a step away from your old life.",
    "You are building a new future, one day at a time.",
    "Your strength is greater than any struggle.",
    "You are not alone; others have walked this path before you.",
    "You are worthy of a life free from addiction.",
    "The best project you’ll ever work on is you.",
    "You are not your worst mistake.",
    "You are allowed to be both a masterpiece and a work in progress.",
    "You are enough, just as you are.",
    "You are rewriting your story every day.",
    "You are not powerless.",
    "You are creating a life you love.",
    "You are more resilient than you realize.",
    "You are choosing hope over fear.",
    "You are making a difference in your own life.",
    "You are learning to love yourself again.",
    "You are breaking the cycle.",
    "You are finding your strength.",
    "You are discovering your true self.",
    "You are taking control of your life.",
    "You are building a brighter future.",
    "You are healing, even when it feels hard.",
    "You are growing through what you’re going through.",
    "You are becoming the person you want to be.",
    "You are enough, and you always have been."
)