name: Build Signed AAB

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode Keystore from secrets
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/my-release-key.jks

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: UT
        run: ./gradlew testDebugUnitTest

      - name: Build signed AAB
        run: ./gradlew bundleRelease

      - name: Get short git hash
        id: githash
        run: echo "GITHASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set version environment variable
        id: setversionname
        run: echo "VERSION_NAME=1.0.6" >> $GITHUB_ENV

      - name: Set AAB filename environment variable
        id: setaabfilename
        run: echo "AAB_FILENAME=noalcohol-${GITHASH}-${VERSION_NAME}.aab" >> $GITHUB_ENV

      - name: Rename AAB for upload
        run: mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/bundle/release/${{ env.AAB_FILENAME }}

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.AAB_FILENAME }}
          path: app/build/outputs/bundle/release/${{ env.AAB_FILENAME }}
